<?php

/**
 * @file
 *
 * In IE6, pops up a IE style dialog notifying the user that there is an update
 * to their browser, hoping to trick the user into updating to the latest
 * version of IE.
 */

/**
 * Implementation of hook_menu().
 */
function ie6update_menu() {
  $items = array();
  $items['admin/config/user-interface/ie6update'] = array(
    'title' => 'IE6 Update',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ie6update_admin_settings'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 * Return the module admin settings form to be rendered
 */
function ie6update_admin_settings() {
  $form = array();
  $form['ie6update_destination_url'] = array(
    '#title' => t('Destination URL'),
    '#description' => t('Where do you want the user directed when they click on the bar?'),
    '#type' => 'textfield',
    '#default_value' => variable_get('ie6update_destination_url', 'http://www.microsoft.com/windows/internet-explorer/default.aspx'),
  );
  $form['ie6update_update_bar_message'] = array(
    '#title' => t('Update Message'),
    '#description' => t('What do you want the user to be told?'),
    '#type' => 'textfield',
    '#default_value' => variable_get('ie6update_update_bar_message', 'Internet Explorer is missing updates required to view this site. Click here to update... '),
  );
  return system_settings_form($form);
}

/**
 * Implementation of hook_page_alter().
 */
function ie6update_page_alter(&$page) {
  global $base_url, $base_path;
  $message = variable_get('ie6update_update_bar_message', 'Internet Explorer is missing updates required to view this site. Click here to update... ');
  $url = variable_get('ie6update_destination_url', 'http://www.microsoft.com/windows/internet-explorer/default.aspx');
  $icon_path = $base_url . '/' . drupal_get_path('module', 'ie6update') .'/images/';
  $js =  '
    <!--[if IE 6]>
      <script type="text/javascript">
        var IE6UPDATE_OPTIONS = {
          icons_path: "' . $icon_path .'",
          message: "' . t(filter_xss_admin($message)) . '",
          url: "' . $url . '"
        }
      </script>
      <script type="text/javascript" src="' . url(drupal_get_path('module', 'ie6update') . '/ie6update.js', array('absolute' => TRUE)) . '"></script>
    <![endif]-->
  ';
  if ($message && $url) {
    $page['page_bottom']['ie6update']= array(
      '#type' => 'markup',
      '#markup' => $js,
    );
  }
}
